apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ig2tg-data
  namespace: ig2tg
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
